### PR TITLE
New Rules

### PR DESCRIPTION
**Pull request by FlawwsX**
This pull request aims to improve every rule in the book!

I read through and improved every rule where possible, adding depth and readability.

### CODE REVIEW

**Review by Nostow — CHANGES_REQUESTED** [review]
Recently there has been a serious uptake in ocean dumping of cars without reason, in particular cop cars. If i recall a few month back there was an announcement that this was against server rules and would fall under LQRP. With that, I dont think many people know this is a rule and being able to report the people doing it becomes near impossible as by the time you get the where the car has been dumped, the person/people are gone. 

It would be great to see this rule added as the random ocean dumping of cars, really ruins their RP for the day. 

Example: I logged onto my cop and 5 minutes later needed to respond to something at VPD Lobby, I locked the car and was in the lobby for around 60 seconds. During that time, someone had stolen the car and proceeded to ocean dump it where it couldnt be recovered.

**Comment by FlawwsX** [comment]
> Recently there has been a serious uptake in ocean dumping of cars without reason, in particular cop cars. If i recall a few month back there was an announcement that this was against server rules and would fall under LQRP. With that, I dont think many people know this is a rule and being able to report the people doing it becomes near impossible as by the time you get the where the car has been dumped, the person/people are gone.
> 
> It would be great to see this rule added as the random ocean dumping of cars, really ruins their RP for the day. or Rather then a rule about specificly ocean dumping cars, a rule regarding certain actions needing a valid roleplay reasons.
> 
> Example: I logged onto my cop and 5 minutes later needed to respond to something at VPD Lobby, I locked the car and was in the lobby for around 60 seconds. During that time, someone had stolen the car and proceeded to ocean dump it where it couldnt be recovered.

Done.

**Review by Arcfull — COMMENTED** [review]
>  "If you find yourself in a situation where you are at a clear disadvantage, such as having a gun pointed at the back of your head while you are unaware, it is expected that you comply with the demands of the other party.",
 Doesn't make sense to use the term "unaware" while reinforcing the idea that demands or orders are being given by the offensive party as the nature of the situation implies the context that all individuals involved are aware of what's happening.

**Comment by MamaPrince** [comment]
For the robbing PD for belongings, I think it would be good to add this example if it in fact does break the rule which to my understanding it does. “For example, wiping police to loot weapons when chances of escape have been offered or arose” (referring to crims wiping pd in an ambush or large block radius to loot pd guns instead of trying to escape)

**Pull request merged**
